version: '2'

services:

  apache-server:
    container_name: apache-proxy
    image: apps4net/apache-proxy:1.0
#    image: apache-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./docker/apache/apache-config.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/logs:/var/log/apache2/