version: '2'

services:

  apache-server:
    image: apps4net/apache:1.2
#    image: apache
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./docker/apache/apache-config.conf:/etc/apache2/sites-enabled/000-default.conf